config/routes.rb
Rails.application.routes.draw do
  resources :pieces, only: [:index, :show] do
    collection do
      get :search
      post :search2
      post :search3

      post :search_results
    end
  end

  root to: "pieces#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/piece.rb
class Piece < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  # GET /pieces
  def index
    @pieces = Piece.all.order('book ASC, ordinal ASC')
  end

  def search
  end

  def search2
    @current_book = params[:book]
    @pieces = Piece.where(book: @current_book)
  end

  def search3
    @current_piece = Piece.find(params[:current_piece])
    all_pieces = Piece.all.order('book ASC, ordinal ASC')
    @pieces_known = all_pieces.index(@current_piece) + 1
  end

  def search_results
    current_piece = Piece.find(params[:current_piece_id])

    all_pieces = Piece.all.order('book ASC, ordinal ASC')
    index_of_current_piece = all_pieces.index(current_piece)
    available_pieces = all_pieces[0..index_of_current_piece]

    number_of_requested_pieces = params[:results_count]
    @pieces = available_pieces.shuffle.first(number_of_requested_pieces.to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PiecePicker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><%= link_to 'PiecePicker', root_path %></h1>
    <%= yield %>
  </body>
</html>

app/views/pieces/_pieces.html.erb
<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Title</th>
      <th>Composer name</th>
    </tr>
  </thead>

  <tbody>
    <% @pieces.each do |piece| %>
      <tr>
        <td><%= piece.book %></td>
        <td><%= piece.title %></td>
        <td><%= piece.composer_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pieces/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Suzuki Pieces</h2>

<%= render partial: "pieces", locals: { pieces: @pieces } %>

app/views/pieces/search.html.erb
<p>Welcome to Piece Picker!</p>

<p>This site was designed by and for Suzuki students to help them quickly and easily choose pieces to practice.</p>

<h2>Search for Pieces - Step 1</h2>

<%= form_tag("/pieces/search2") do %>
  <%= label_tag "book", "What book are you currently on?" %>
  <%= select_tag "book", options_for_select((1..8)), autofocus: true %>

  <p><%= submit_tag "Next ->" %></p>
<% end %>

<%= link_to "View All Pieces", pieces_path %>

app/views/pieces/search2.html.erb
<h2>Search for Pieces - Step 2</h2>

<h3>You are working in Book <%= @current_book %></h3>

<%= form_tag("/pieces/search3") do %>
  <%= label_tag "current_piece", "What piece are you currently on?" %>
  <%= select_tag "current_piece", options_from_collection_for_select(@pieces, :id, :title), autofocus: true %>

  <p><%= submit_tag "Next ->" %></p>
<% end %>

<%= link_to "View All Pieces", pieces_path %>

app/views/pieces/search3.html.erb
<h2>Search for Pieces - Step 3</h2>

<%= form_tag("/pieces/search_results") do %>
  <%= hidden_field_tag "current_piece_id", @current_piece.id %>

  <%= label_tag "results_count", "How many pieces do you want to practice?" %>
  <%= select_tag "results_count", options_for_select(1..@pieces_known), autofocus: true %>

  <p><%= submit_tag "Find My Pieces ->" %></p>
<% end %>

<%= link_to "View All Pieces", pieces_path %>

app/views/pieces/search_results.html.erb
<h2>Repertoire</h2>

<p>These are the pieces selected for you to practice:</p>

<%= render partial: "pieces", locals: { pieces: @pieces } %>